global:
  isEKS:
    enabled: false
  gateway:
    enabled: true

map-service:
  image:
    repository: buried-marks-map-service
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  securityContext: {}
  podSecurityContext: {}
  livenessProbe: {}
  readinessProbe: {}
  httpRoute:
    enabled: true

auth-service:
  image:
    repository: buried-marks-auth-service
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  securityContext: {}
  podSecurityContext: {}
  livenessProbe: {}
  readinessProbe: {}
  httpRoute:
    enabled: true

mail-service:
  image:
    repository: buried-marks-mail-service
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  securityContext: {}
  podSecurityContext: {}
  httpRoute:
    enabled: true

voting-service:
  image:
    repository: buried-marks-voting-service
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  securityContext: {}
  podSecurityContext: {}
  httpRoute:
    enabled: true

login-front:
  image:
    repository: buried-marks-login-front
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  httpRoute:
    enabled: true

map-front:
  image:
    repository: buried-marks-map-front
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  httpRoute:
    enabled: true

voting-front:
  image:
    repository: buried-marks-voting-front
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  httpRoute:
    enabled: true

admin-front:
  image:
    repository: buried-marks-admin-front
    pullPolicy: Never
    tag: "latest"
  imagePullSecrets: []
  httpRoute:
    enabled: true
