global:
  aws:
    region: eu-north-1
  domain: marks.birds.pp.ua
  env: prod
  isEKS:
    enabled: true
  gateway:
    enabled: false
  secrets:
    buried-marks-helm-authentication-microservice: "auth-service"
    buried-marks-helm-map-microservice: "map-service"
    buried-marks-helm-voting-microservice: "voting-service"
    buried-marks-helm-mail-microservice: "mail-service"
    buried-marks-helm-mcp: "mcp"

elb:
  certificateArn: "arn:aws:acm:eu-north-1:833822972731:certificate/0dfdb5cb-1796-46e3-a87c-9b22e1addb2e"

gateway:
  gatewayClassName: amazon-vpc-lattice
  controllerName: ""

map-service:
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 2
  httpRoute:
    enabled: false
  livenessProbe:
    httpGet:
      path: /health/
      port: 9001
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /health/
      port: 9001
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 10
  mariadb:
    primary:
      persistence:
        enabled: true
        size: 1Gi

auth-service:
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-authentication-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 2
  httpRoute:
    enabled: false
  livenessProbe: {}
  readinessProbe: {}
  postgresql:
    primary:
      persistence:
        enabled: true
        size: 3Gi

mail-service:
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-mail-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 1
  httpRoute:
    enabled: false
  valkey:
    primary:
      persistence:
        enabled: true
        size: 1Gi

voting-service:
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 2
  httpRoute:
    enabled: false
  livenessProbe: {}
  readinessProbe: {}
  postgresql:
    primary:
      persistence:
        enabled: true
        size: 5Gi

login-front:
  replicaCount: 2
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-login-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

map-front:
  replicaCount: 2
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

voting-front:
  replicaCount: 2
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

admin-front:
  replicaCount: 2
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-admin-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

mcp:
  replicaCount: 2
  image:
    repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-mcp
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 15d
      replicas: 2
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 4Gi
      # storageSpec:
      #   volumeClaimTemplate:
      #     spec:
      #       resources:
      #         requests:
      #           storage: 30Gi

  grafana:
    # persistence:
    #   size: 10Gi

  alertmanager:
    enabled: true
    config:
      receivers:
        - name: "slack"
          slack_configs:
            - api_url: ${SLACK_API_URL}
              channel: ${SLACK_CHANNEL}
              send_resolved: true
