global:
  isEKS:
    enabled: true

map-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

auth-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-authentication-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

mail-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-mail-microservice
    pullPolicy: IfNotPresent
    tag: "latest"

voting-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

login-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-login-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

map-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

voting-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

admin-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-admin-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false
