global:
  isEKS:
    enabled: true
  gateway:
    enabled: false

gateway:
  gatewayClassName: amazon-vpc-lattice
  controllerName: ""

map-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

auth-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-authentication-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

mail-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-mail-microservice
    pullPolicy: IfNotPresent
    tag: "latest"

voting-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

login-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-login-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

map-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

voting-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

admin-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-admin-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi

  alertmanager:
    enabled: true
    config:
      receivers:
        - name: "slack"
          slack_configs:
            - api_url: "https://hooks.slack.com/services/XXX/XXX/XXX"
              channel: "#alerts-stage"
              send_resolved: true
