global:
  domain: marks.stage.command-line.top
  env: stage
  isEKS:
    enabled: true
  gateway:
    enabled: false

elb:
  certificateArn: "arn:aws:acm:eu-north-1:492052863680:certificate/e1eefdab-e668-4d1d-9649-d53a68fff7c4"

gateway:
  gatewayClassName: amazon-vpc-lattice
  controllerName: ""

map-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

auth-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-authentication-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

mail-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-mail-microservice
    pullPolicy: IfNotPresent
    tag: "latest"

voting-service:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-microservice
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

login-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-login-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

map-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

voting-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

admin-front:
  replicaCount: 2
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-admin-front
    pullPolicy: IfNotPresent
    tag: "latest"
  httpRoute:
    enabled: false

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi

  alertmanager:
    enabled: true
    config:
      receivers:
        - name: "slack"
          slack_configs:
            - api_url: ${SLACK_API_URL}
              channel: ${SLACK_CHANNEL}
              send_resolved: true
