environments:
  dev:
    values:
      - env: dev
        domain: marks.dev.birds.pp.ua
        baseDomain: birds.pp.ua
  stage:
    values:
      - env: stage
        domain: marks.stage.command-line.top
        baseDomain: command-line.top
  prod:
    values:
      - env: prod
        domain: marks.command-line.top
        baseDomain: command-line.top
---

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: external-secrets
  url: https://charts.external-secrets.io

releases:
- name: gateway
  chart: charts/gateway
  namespace: buried-marks
  condition: global.gateway.enabled
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: aws-gateway-api-controller
  chart: oci://public.ecr.aws/aws-controllers-k8s/aws-gateway-api-controller
  namespace: aws-application-networking-system
  createNamespace: true
  condition: global.isEKS.enabled
  set:
    - name: aws.region
      value: eu-north-1
    - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
      value: arn:aws:iam::531331080468:role/aws-gateway-api-controller

- name: auth-service
  chart: charts/auth-service
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: mail-service
  chart: charts/mail-service
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: map-service
  chart: charts/map-service
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: voting-service
  chart: charts/voting-service
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: login-front
  chart: charts/login-front
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: map-front
  chart: charts/map-front
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: voting-front
  chart: charts/voting-front
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: admin-front
  chart: charts/admin-front
  namespace: buried-marks
  values:
  - values/{{ .Environment.Name }}-values.yaml

- name: monitoring
  chart: charts/monitoring
  namespace: monitoring
  createNamespace: true
  values:
  - values/{{ .Environment.Name }}-values.yaml
