global:
  aws:
    region: eu-north-1
  secrets:
    map-service: buried-marks/map-service
    auth-service: buried-marks/auth-service
    mail-service: buried-marks/mail-service
    voting-service: buried-marks/voting-service
    map-front: buried-marks/map-front
  isEKS: false
  gateway:
    name: buried-marks-gateway
    # hostnames:
    # - buried-marks.local
