global:
  aws:
    region: eu-north-1
  secrets:
    map-service: buried-marks/map-service
    auth-service: buried-marks/map-service
    mail-service: buried-marks/map-service
    voting-service: buried-marks/map-service
  isEKS: false
  gateway:
    name: buried-marks-gateway
    hostnames:
      - buried-marks.local
