apiVersion: v2
name: voting-front
description: Buried Marks voting-front microservice
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"
