replicaCount: 1

image:
  repository: 492052863680.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-front
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
# - name: ecr-secret

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8080

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
  - name: buried-marks-gateway
    sectionName: https
  # hostnames:
  # - buried-marks.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /voting/

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

livenessProbe: {}

readinessProbe:
  httpGet:
    path: /voting/
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
