replicaCount: 1

podAnnotations:
  consul.hashicorp.com/connect-inject: "true"

image:
  repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-admin-front
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
# - name: ecr-secret

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8080

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
  - name: buried-marks-gateway
    sectionName: https
  # hostnames:
  # - buried-marks.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /admin/

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

livenessProbe: {}

readinessProbe:
  httpGet:
    path: /admin/
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
