apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.envSecret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ .Values.envSecret }}
    creationPolicy: Owner
  # data:
  # - secretKey: secret-key-to-be-managed
  #   remoteRef:
  #     key: provider-key
  #     version: provider-key-version
  #     property: provider-key-property
  dataFrom:
  - key: buried-marks/map-service
