gatewayClassName: aws-envoy
namespace: buried-marks
controllerName: gateway.envoyproxy.io/gatewayclass-controller

aws:
  certificateArn: ""

listeners:
  - name: http
    port: 80
    protocol: HTTP
  - name: https
    port: 443
    protocol: HTTP
