admin-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-admin-front
    pullPolicy: IfNotPresent

login-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-login-front
    pullPolicy: IfNotPresent

map-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-front
    pullPolicy: IfNotPresent

voting-front:
  image:
    repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-front
    pullPolicy: IfNotPresent