image:
  # repository: 531331080468.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-map-microservice
  repository: buried-marks-map-service
  pullPolicy: Never
  tag: "latest"

imagePullSecrets: []

securityContext: {}
podSecurityContext: {}

envSecret: map-service-secret

env:
  DATABASE_HOST: map-service-db

volumeMounts:
  - name: jwt-public-key
    mountPath: "app/ec_public.key"
    subPath: ec_public.key
    readOnly: false

livenessProbe: {}
readinessProbe: {}

mariadb:
  auth:
    existingSecret: map-service-secret
    database: buriedmarks
    username: buriedmarks
  primary:
    persistence:
      enabled: false
