apiVersion: v2
name: buried-marks-helm-map-front
description: Buried Marks map-front microservice
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
- name: common
  version: "0.1.0"
  repository: "file://../common"
