replicaCount: 1

image:
  repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-voting-microservice
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
# - name: ecr-secret

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8900

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
  - name: buried-marks-gateway
    sectionName: https
  # hostnames:
  # - buried-marks.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/polls/
  - matches:
    - path:
        type: PathPrefix
        value: /docs
  - matches:
    - path:
        type: PathPrefix
        value: /openapi.json

resources: {}

envSecret: voting-service-secret
awsSecretName: buried-marks/voting-service

livenessProbe: {}
readinessProbe: {}

volumes:
- name: jwt-public-key
  secret:
    secretName: voting-service-secret
    items:
      - key: JWT_PUBLIC_KEY
        path: public.pem
- name: jwt-private-key
  secret:
    secretName: voting-service-secret
    items:
      - key: JWT_PRIVATE_KEY
        path: private.pem

volumeMounts:
- name: jwt-public-key
  mountPath: "/tmp/jwt_public_key/ec_public.key"
  subPath: public.pem
  readOnly: true
- name: jwt-private-key
  mountPath: "/tmp/jwt_private_key/ec_private.key"
  subPath: private.pem
  readOnly: true

db:
  host: voting-service-postgresql
  port: 5432

postgresql:
  auth:
    existingSecret: voting-service-secret
    database: voting_db
    username: admin
  primary:
    persistence:
      enabled: false

global:
  aws:
    region: eu-north-1
  secrets:
    voting-service: buried-marks/voting-service
    buried-marks-helm-voting-microservice: buried-marks/voting-service
