replicaCount: 1

image:
  repository: 833822972731.dkr.ecr.eu-north-1.amazonaws.com/buried-marks-authentication-microservice
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
# - name: ecr-secret

serviceAccount:
  create: true
  # Exact name is needed for EKS Pod Identity Association for RDS
  name: "auth-service"

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8000

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
  - name: buried-marks-gateway
    sectionName: https
  # hostnames:
  # - buried-marks.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/login/
  - matches:
    - path:
        type: PathPrefix
        value: /api/token/
  - matches:
    - path:
        type: PathPrefix
        value: /api/update-password/
  - matches:
    - path:
        type: PathPrefix
        value: /api/emails/
  - matches:
    - path:
        type: PathPrefix
        value: /api/users/
  - matches:
    - path:
        type: PathPrefix
        value: /architect/send-email/
  - matches:
    - path:
        type: PathPrefix
        value: /invite/
  - matches:
    - path:
        type: PathPrefix
        value: /accept-invite/
  - matches:
      - path:
          type: PathPrefix
          value: /architect/mcp-moderation/

resources: {}

envSecret: auth-service-secret
awsSecretName: buried-marks/auth-service

volumes:
- name: jwt-public-key
  secret:
    secretName: auth-service-secret
    items:
    - key: JWT_PUBLIC_KEY
      path: public.pem
- name: jwt-private-key
  secret:
    secretName: auth-service-secret
    items:
    - key: JWT_PRIVATE_KEY
      path: private.pem

volumeMounts:
- name: jwt-public-key
  mountPath: "/app/public.pem"
  subPath: public.pem
  readOnly: true
- name: jwt-private-key
  mountPath: "/app/private.pem"
  subPath: private.pem
  readOnly: true

db:
  host: auth-service-postgresql
  port: 5432

# postgresql:
#   auth:
#     existingSecret: auth-service-secret
#     database: auth_db
#     username: db_admin
#   primary:
#     persistence:
#       enabled: false

global:
  aws:
    region: eu-north-1
  secrets:
    auth-service: buried-marks/auth-service
    buried-marks-helm-authentication-microservice: buried-marks/auth-service
